### ISSUE TITLE
Better network visualization

### ISSUE THREAD

**Issue by phiros** [leanovate/akka-typed-raft#2]
As a starting point we could use:
https://github.com/dborzov/netvis

demo:
https://www.borzov.ca/netvis/

Seems to support most of the functionality that we need. Only downside of this library is that it is more or less abandoned for more than 3 years.

**Comment by Jentsch** [comment]
The implementation used by raft.github.io https://github.com/ongardie/raftscope

**Comment by Jentsch** [comment]
Maybe we could use d3.js. E.g. a forced graph, where the force between two nodes is the frequencies they exchange messages. (Example here: https://bl.ocks.org/mbostock/4062045). It wouldn't look like the visualization on https://raft.github.io/, but how cares?

The visualization the would adapt to active topology to the network. Leader should be end up surround by its follower and disconnected nodes would separate von other nodes. Doesn't sound bad for me. Also this require very few changes if we later on like to show more nodes (e.g. clients) or like to change the algorithm.

This would be relatively easy to implement and d3 is a very active solid project. Right know I don't know how to place little wandering circles in the graph to symbolize the messages in the network.

**Comment by Jentsch** [comment]
We have now some visualization:

![grafik](https://user-images.githubusercontent.com/818446/36221383-3571e7d0-11be-11e8-9a21-5e3c771a7414.png)

It's not perfect, but better than nothing. I'll close this issue, late we can open new ones for specific improvements.
